#!/bin/bash

rm -rf ./build
npm run build
cp ./package-lock.json ./build
cd ./build
mv src app
../scripts/gen-prod-package-json package.json package.json
find . -wholename '*.d.ts' -delete
find . -wholename '*.test.js' -delete
cd ..