name: Deploy

on:
  deployment:
    branches-ignore:
      - '**'
    tags:
      - v*
jobs:
  Verify:
    environment: ${{ github.event.deployment.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Print event data
        env:
          EVENT: ${{ toJSON( github.event ) }}
        run: echo "$EVENT"
