name: Release Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.5
        with:
          node-version: 14
      - name: Setup and install dependencies
        run: |
          npm ci
      - name: Unit tests and Coverage
        run: |
          npm run test
      - name: Newman tests
        run: |
          npm run test:newman
  Publish:
      runs-on: ubuntu-latest
      if: ${{ github.ref == 'refs/heads/main' }}
      needs: [Verify]
      steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.5
        with:
          node-version: 14
      - name: Package 📦 
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m0q0z2r6
          npm ci
          npm run build
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Publish 🚀 
        run: npm run release
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
